# Generated by Django 5.2.8 on 2026-02-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('Painting & Decorating', 'Painting & Decorating'), ('Wallpaper Installation', 'Wallpaper Installation'), ('General Cleaning', 'General Cleaning'), ('Gardening', 'Gardening'), ('Lawn Care', 'Lawn Care'), ('Weed Control', 'Weed Control'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
