# Generated by Django 5.2.8 on 2026-06-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanintegratedservices_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(choices=[('Painting & Decorating', 'Painting & Decorating'), ('Air Condition Services', 'Air Condition Services'), ('Wallpaper Installation', 'Wallpaper Installation'), ('General Cleaning', 'General Cleaning'), ('Gardening', 'Gardening'), ('Lawn Care', 'Lawn Care'), ('Weed Control', 'Weed Control'), ('Other', 'Other')], max_length=100),
        ),
    ]
